# Dependency detection, mirroring meson.build sections.
# SPDX-License-Identifier: MIT

# --- zlib ---
set(MESA_ZLIB_AUTO OFF)
if(MESA_OP_ZLIB STREQUAL "auto" OR MESA_OP_ZLIB STREQUAL "enabled")
  pkg_check_modules(PC_ZLIB IMPORTED_TARGET zlib)
  if(PC_ZLIB_FOUND)
    set(dep_zlib PkgConfig::PC_ZLIB)
    add_compile_definitions(-DHAVE_ZLIB)
    set(MESA_ZLIB_AUTO ON)
  elseif(MESA_OP_ZLIB STREQUAL "enabled")
    message(FATAL_ERROR "mesa: zlib not found")
  endif()
else()
  set(dep_zlib "")
endif()
set(with_compression OFF)
if(dep_zlib)
  set(with_compression ON)
endif()

# --- zstd ---
if(MESA_OP_ZSTD STREQUAL "auto" OR MESA_OP_ZSTD STREQUAL "enabled")
  pkg_check_modules(PC_ZSTD IMPORTED_TARGET libzstd)
  if(PC_ZSTD_FOUND)
    set(dep_zstd PkgConfig::PC_ZSTD)
    add_compile_definitions(-DHAVE_ZSTD)
    set(with_compression ON)
  elseif(MESA_OP_ZSTD STREQUAL "enabled")
    message(FATAL_ERROR "mesa: libzstd not found")
  endif()
else()
  set(dep_zstd "")
endif()
if(with_compression)
  add_compile_definitions(-DHAVE_COMPRESSION)
endif()

# --- expat ---
set(dep_expat "")
if(NOT MESA_OP_EXPAT STREQUAL "disabled")
  pkg_check_modules(PC_EXPAT IMPORTED_TARGET expat)
  if(PC_EXPAT_FOUND)
    set(dep_expat PkgConfig::PC_EXPAT)
  endif()
endif()

# --- libdrm ---
set(dep_libdrm "")
if(system_has_kms_drm)
  pkg_check_modules(PC_LIBDRM IMPORTED_TARGET libdrm)
  if(PC_LIBDRM_FOUND)
    set(dep_libdrm PkgConfig::PC_LIBDRM)
    add_compile_definitions(-DHAVE_LIBDRM)
  endif()
endif()
set(dep_libdrm_amdgpu "")
set(dep_libdrm_intel "")
pkg_check_modules(PC_LIBDRM_AMDGPU IMPORTED_TARGET libdrm_amdgpu)
if(PC_LIBDRM_AMDGPU_FOUND)
  set(dep_libdrm_amdgpu PkgConfig::PC_LIBDRM_AMDGPU)
endif()
pkg_check_modules(PC_LIBDRM_INTEL IMPORTED_TARGET libdrm_intel)
if(PC_LIBDRM_INTEL_FOUND)
  set(dep_libdrm_intel PkgConfig::PC_LIBDRM_INTEL)
endif()

# --- threads ---
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  set(dep_thread "")
else()
  set(dep_thread Threads::Threads)
endif()

# --- libm / dl ---
set(dep_m "${M_LIB}")
set(dep_dl "")
if(NOT CMAKE_SYSTEM_NAME STREQUAL "Windows" AND NOT __mesa_dlopen)
  set(dep_dl "${CMAKE_DL_LIBS}")
endif()

# --- libelf ---
set(dep_elf "")
pkg_check_modules(PC_LIBELF IMPORTED_TARGET libelf)
if(PC_LIBELF_FOUND)
  set(dep_elf PkgConfig::PC_LIBELF)
  add_compile_definitions(-DUSE_LIBELF)
else()
  find_library(ELF_LIB elf)
  if(ELF_LIB)
    set(dep_elf "${ELF_LIB}")
    add_compile_definitions(-DUSE_LIBELF)
  endif()
endif()

# --- libunwind ---
if(MESA_OP_LIBUNWIND STREQUAL "enabled" OR MESA_OP_LIBUNWIND STREQUAL "auto")
  pkg_check_modules(PC_UNWIND IMPORTED_TARGET libunwind)
  if(PC_UNWIND_FOUND)
    set(dep_unwind PkgConfig::PC_UNWIND)
    add_compile_definitions(-DHAVE_LIBUNWIND)
  elseif(MESA_OP_LIBUNWIND STREQUAL "enabled")
    message(FATAL_ERROR "mesa: libunwind not found")
  endif()
endif()

# --- valgrind ---
set(dep_valgrind "")
if(MESA_OP_VALGRIND STREQUAL "enabled" OR MESA_OP_VALGRIND STREQUAL "auto")
  pkg_check_modules(PC_VALGRIND IMPORTED_TARGET valgrind)
  if(PC_VALGRIND_FOUND)
    set(dep_valgrind PkgConfig::PC_VALGRIND)
    add_compile_definitions(-DHAVE_VALGRIND)
  endif()
endif()

# --- libdisplay-info ---
set(dep_display_info "")
if(MESA_OP_DISPLAY_INFO STREQUAL "enabled" OR MESA_OP_DISPLAY_INFO STREQUAL "auto")
  pkg_check_modules(PC_DISPLAY_INFO IMPORTED_TARGET libdisplay-info)
  if(PC_DISPLAY_INFO_FOUND)
    set(dep_display_info PkgConfig::PC_DISPLAY_INFO)
    add_compile_definitions(-DHAVE_LIBDISPLAY_INFO)
  endif()
endif()

# --- libudev ---
set(dep_libudev "")
pkg_check_modules(PC_LIBUDEV IMPORTED_TARGET libudev)
if(PC_LIBUDEV_FOUND)
  set(dep_libudev PkgConfig::PC_LIBUDEV)
  add_compile_definitions(-DHAVE_LIBUDEV)
endif()

# --- glvnd ---
set(dep_glvnd "")
pkg_check_modules(PC_GLVND IMPORTED_TARGET libglvnd)
if(PC_GLVND_FOUND AND NOT with_platform_windows AND NOT with_glx STREQUAL "xlib")
  set(dep_glvnd PkgConfig::PC_GLVND)
  set(with_glvnd ON)
else()
  set(with_glvnd OFF)
endif()
if(with_glvnd)
  add_compile_definitions(-DUSE_LIBGLVND=1)
endif()

# --- LLVM ---
# Mesa uses llvm-config (config-tool method) on non-Windows; find_package(LLVM)
# is not used because LLVM's exports file is unreliable with multiple versions.
set(dep_llvm "")
set(llvm_with_orcjit ${MESA_OP_LLVM_ORCJIT})
set(with_clc OFF)
if(with_llvm STREQUAL "ON" OR with_llvm STREQUAL "AUTO")
  if(MESA_OP_SYSTEM_LLVM)
    find_program(LLVM_CONFIG_EXE llvm-config-22 llvm-config-21 llvm-config-20 llvm-config-19 llvm-config-18 llvm-config-17 llvm-config-16 llvm-config-15 llvm-config)
  endif()
  if(LLVM_CONFIG_EXE)
    execute_process(COMMAND ${LLVM_CONFIG_EXE} --version OUTPUT_VARIABLE LLVM_VERSION_STRING OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND ${LLVM_CONFIG_EXE} --includedir OUTPUT_VARIABLE LLVM_INCLUDE_DIRS OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND ${LLVM_CONFIG_EXE} --libdir OUTPUT_VARIABLE LLVM_LIBRARY_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND ${LLVM_CONFIG_EXE} --shared-mode OUTPUT_VARIABLE LLVM_SHARED_MODE OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(LLVM_FOUND TRUE)
  endif()
endif()
if(LLVM_FOUND)
  set(with_llvm ON)
  set(llvm_components
    core mcjit executionengine bitwriter engine mcdisassembler scalaropts
    transformutils instcombine native)
  if(host_cpu_family STREQUAL "x86_64" OR host_cpu_family STREQUAL "x86" OR host_cpu_family STREQUAL "aarch64")
    # MCJIT supported
  else()
    set(llvm_with_orcjit ON)
  endif()
  execute_process(
    COMMAND ${LLVM_CONFIG_EXE} --libs ${llvm_components}
    OUTPUT_VARIABLE LLVM_LIBS OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(
    COMMAND ${LLVM_CONFIG_EXE} --system-libs
    OUTPUT_VARIABLE LLVM_SYSTEM_LIBS OUTPUT_STRIP_TRAILING_WHITESPACE)
  set(LLVM_LIBS "${LLVM_LIBS} ${LLVM_SYSTEM_LIBS}")
  separate_arguments(LLVM_LIBS_LIST UNIX_COMMAND "${LLVM_LIBS}")
  # add definitions
  execute_process(COMMAND ${LLVM_CONFIG_EXE} --cppflags OUTPUT_VARIABLE LLVM_CPPFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
  separate_arguments(LLVM_CPPFLAGS_LIST UNIX_COMMAND "${LLVM_CPPFLAGS}")
  foreach(_f IN LISTS LLVM_CPPFLAGS_LIST)
    if(_f MATCHES "^-D")
      string(SUBSTRING "${_f}" 2 -1 _def)
      add_compile_definitions(-D${_def})
    endif()
  endforeach()
  add_compile_definitions(
    -DMESA_LLVM_VERSION_STRING="${LLVM_VERSION_STRING}"
    -DLLVM_IS_SHARED=1
    -DGALLIVM_USE_ORCJIT=${llvm_with_orcjit})
  if(draw_with_llvm STREQUAL "AUTO")
    set(draw_with_llvm ON)
  endif()
  add_compile_definitions(-DDRAW_LLVM_AVAILABLE=1)
  message(STATUS "Mesa LLVM: ${LLVM_VERSION_STRING} at ${LLVM_LIBRARY_DIR}")
else()
  set(with_llvm OFF)
  set(draw_with_llvm OFF)
  set(amd_with_llvm OFF)
endif()
set(amd_with_llvm OFF)  # AMD LLVM path not enabled in this port

# glslang
if(MESA_GLSLANG)
  execute_process(COMMAND ${MESA_GLSLANG} --version OUTPUT_VARIABLE _glslang_out OUTPUT_STRIP_TRAILING_WHITESPACE)
  set(glslang_depfile "--depfile;@DEPFILE@")
endif()

# --- SPIRV-Tools ---
set(dep_spirv_tools "")
if(MESA_OP_SPIRV_TOOLS STREQUAL "enabled" OR MESA_OP_SPIRV_TOOLS STREQUAL "auto")
  pkg_check_modules(PC_SPIRVTOOLS IMPORTED_TARGET SPIRV-Tools)
  if(PC_SPIRVTOOLS_FOUND)
    set(dep_spirv_tools PkgConfig::PC_SPIRVTOOLS)
    add_compile_definitions(-DHAVE_SPIRV_TOOLS)
  elseif(MESA_OP_SPIRV_TOOLS STREQUAL "enabled")
    message(FATAL_ERROR "mesa: SPIRV-Tools not found")
  endif()
endif()

# --- X11 / xcb ---
set(dep_x11 "")
set(dep_xext "")
set(dep_x11_xcb "")
set(dep_xcb "")
set(dep_xcb_keysyms "")
set(dep_xcb_glx "")
set(dep_xcb_dri3 "")
set(dep_glproto "")
set(dep_xxf86vm "")
set(dep_xcb_present "")
set(dep_xcb_sync "")
set(dep_xcb_xfixes "")
set(dep_xshmfence "")
set(dep_xcb_xrandr "")
set(dep_xcb_shm "")
set(dep_xlib_xrandr "")
set(with_xcb_keysyms OFF)
set(with_dri3_explicit_sync OFF)
if(with_platform_x11)
  pkg_check_modules(PC_XCB IMPORTED_TARGET xcb)
  if(PC_XCB_FOUND)
    set(dep_xcb PkgConfig::PC_XCB)
  endif()
  pkg_check_modules(PC_XCB_XRANDR IMPORTED_TARGET xcb-randr)
  if(PC_XCB_XRANDR_FOUND)
    set(dep_xcb_xrandr PkgConfig::PC_XCB_XRANDR)
  endif()
  pkg_check_modules(PC_X11 IMPORTED_TARGET x11)
  if(PC_X11_FOUND)
    set(dep_x11 PkgConfig::PC_X11)
  endif()
  pkg_check_modules(PC_XEXT IMPORTED_TARGET xext)
  if(PC_XEXT_FOUND)
    set(dep_xext PkgConfig::PC_XEXT)
  endif()
  pkg_check_modules(PC_XCB_GLX IMPORTED_TARGET xcb-glx)
  if(PC_XCB_GLX_FOUND)
    set(dep_xcb_glx PkgConfig::PC_XCB_GLX)
  endif()
  pkg_check_modules(PC_XCB_SHM IMPORTED_TARGET xcb-shm)
  if(PC_XCB_SHM_FOUND)
    set(dep_xcb_shm PkgConfig::PC_XCB_SHM)
  endif()
  pkg_check_modules(PC_X11_XCB IMPORTED_TARGET x11-xcb)
  if(PC_X11_XCB_FOUND)
    set(dep_x11_xcb PkgConfig::PC_X11_XCB)
  endif()
  pkg_check_modules(PC_XCB_DRI3 IMPORTED_TARGET xcb-dri3)
  if(PC_XCB_DRI3_FOUND)
    set(dep_xcb_dri3 PkgConfig::PC_XCB_DRI3)
  endif()
  pkg_check_modules(PC_XCB_PRESENT IMPORTED_TARGET xcb-present)
  if(PC_XCB_PRESENT_FOUND)
    set(dep_xcb_present PkgConfig::PC_XCB_PRESENT)
  endif()
  pkg_check_modules(PC_XSHMFENCE IMPORTED_TARGET xshmfence)
  if(PC_XSHMFENCE_FOUND)
    set(dep_xshmfence PkgConfig::PC_XSHMFENCE)
  endif()
  pkg_check_modules(PC_XCB_SYNC IMPORTED_TARGET xcb-sync)
  if(PC_XCB_SYNC_FOUND)
    set(dep_xcb_sync PkgConfig::PC_XCB_SYNC)
  endif()
  pkg_check_modules(PC_XCB_XFIXES IMPORTED_TARGET xcb-xfixes)
  if(PC_XCB_XFIXES_FOUND)
    set(dep_xcb_xfixes PkgConfig::PC_XCB_XFIXES)
  endif()
  pkg_check_modules(PC_XXF86VM IMPORTED_TARGET xxf86vm)
  if(PC_XXF86VM_FOUND)
    set(dep_xxf86vm PkgConfig::PC_XXF86VM)
  endif()
  pkg_check_modules(PC_XCB_KEYSYMS IMPORTED_TARGET xcb-keysyms)
  if(PC_XCB_KEYSYMS_FOUND)
    set(dep_xcb_keysyms PkgConfig::PC_XCB_KEYSYMS)
    set(with_xcb_keysyms ON)
    add_compile_definitions(-DXCB_KEYSYMS_AVAILABLE)
  endif()
  pkg_check_modules(PC_XRANDR IMPORTED_TARGET xrandr)
  if(PC_XRANDR_FOUND)
    set(dep_xlib_xrandr PkgConfig::PC_XRANDR)
  endif()
  if(with_dri_platform STREQUAL "drm")
    add_compile_definitions(-DHAVE_X11_DRM)
  endif()
endif()

# --- wayland ---
set(dep_wayland_client "")
set(dep_wayland_server "")
set(dep_wayland_egl "")
if(with_platform_wayland)
  pkg_check_modules(PC_WAYLAND_CLIENT IMPORTED_TARGET wayland-client)
  pkg_check_modules(PC_WAYLAND_SERVER IMPORTED_TARGET wayland-server)
  pkg_check_modules(PC_WAYLAND_EGL_BACKEND IMPORTED_TARGET wayland-egl-backend)
  pkg_check_modules(PC_WAYLAND_PROTOCOLS IMPORTED_TARGET wayland-protocols)
  if(PC_WAYLAND_CLIENT_FOUND)
    set(dep_wayland_client PkgConfig::PC_WAYLAND_CLIENT)
  endif()
  if(PC_WAYLAND_SERVER_FOUND)
    set(dep_wayland_server PkgConfig::PC_WAYLAND_SERVER)
  endif()
  if(PC_WAYLAND_EGL_BACKEND_FOUND)
    set(dep_wayland_egl PkgConfig::PC_WAYLAND_EGL_BACKEND)
  endif()
endif()

# --- openmp (llvmpipe) ---
if(host_cpu_family STREQUAL "x86_64" AND CMAKE_C_COMPILER_ID STREQUAL "GNU")
  find_package(OpenMP QUIET)
  if(OpenMP_C_FOUND)
    add_compile_definitions(-DHAVE_OPENMP)
    set(dep_openmp OpenMP::OpenMP_C)
  endif()
endif()

# --- sensors ---
if(MESA_OP_LMSENSORS)
  find_library(SENSORS_LIB sensors)
  if(SENSORS_LIB)
    set(dep_lmsensors "${SENSORS_LIB}")
    add_compile_definitions(-DHAVE_LIBSENSORS=1)
  endif()
endif()

# --- lua (freedreno tools) ---
set(dep_lua "")
pkg_check_modules(PC_LUA IMPORTED_TARGET lua54 lua5.4 lua-5.4 lua53 lua5.3 lua-5.3 lua)
if(PC_LUA_FOUND)
  set(dep_lua PkgConfig::PC_LUA)
endif()

message(STATUS "Mesa CMake: dependencies resolved")
